# Generated by Django 5.1.1 on 2024-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip-адрес')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('http_method', models.CharField(max_length=10, verbose_name='Методы http')),
                ('uri', models.TextField(verbose_name='URI')),
                ('status_code', models.IntegerField(verbose_name='Статус код')),
                ('response_size', models.IntegerField()),
            ],
        ),
    ]
