# Generated by Django 5.1.1 on 2024-09-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxlog',
            name='response_size',
            field=models.IntegerField(verbose_name='Размер ответа'),
        ),
    ]
